### ISSUE TITLE
FluShortInfoBar 手动关闭异常.

### ISSUE THREAD

**Issue by 860000023** [mowangshuying/CppQtFluentUi888#10]
FluShortInfoBar 的示例多点击出提示框后,在他自动消失前点X的按钮,就会异常
void FluShortInfoBar::disappear() 的
m_opacityAni->setStartValue(1);

我认为应该是对象已经释放,但是定时器执行的时候没有判断对象是否还存在.所以我修改了这个函数,在
```
void FluShortInfoBar::disappear()
里面添加
QPointer<LYShortInfoBar> ptr(this);
QTimer::singleShot(m_nDisappearDuration, [=]() {
	if (!ptr)
		return;  // 如果对象已经被删除，就返回
```

这样好像就解决了.

**Comment by mowangshuying** [comment]
点击关闭按钮后，FluInfoBarMgr中会把这个InfoBar从m_infoBarMap中移除掉，移除掉的话应该就不会调用disappear这个函数了. 有一种情况是正在调用disappear函数了，你点击关闭它，这个时候对象销毁，可能会导致崩溃，可以增加点日志再次确认下.

**Comment by mowangshuying** [comment]
QPointer<LYShortInfoBar> ptr(this); 这句代码没有看懂， LYShortInfoBar是你重新定义的一个类吗？

**Comment by 860000023** [comment]
`void FluShortInfoBar::disappear()
{
    // m_nDisappearDuration = duration;
    if (m_nDisappearDuration > 0 && !m_bDisappearing)
    {
        m_bDisappearing = true;
        QPointer <FluShortInfoBar>  ptr(this);
        QTimer::singleShot(m_nDisappearDuration, [=]() {
			if (!ptr)
				return;  // 如果对象已经被删除，就返回
            m_opacityAni->setDuration(500);
            m_opacityAni->setStartValue(1);
            m_opacityAni->setEndValue(0);
            connect(m_opacityAni, &QPropertyAnimation::finished, [=]() { m_closeBtn->clicked(); });
            m_opacityAni->start();
        });
    }
}`


如果m_nDisappearDuration 你改成2000.就能看到效果了.如果你信息框出来,就点X关掉.因为要等2秒才能执行到下面m_opacityAni->setDuration(500); 这一行.这时候对象已经没了.所以就会异常.QPointer 是用来跟踪FluShortInfoBar对象的生命周期

**Comment by 860000023** [comment]
FluInfoBarMgr::getInstance()->addInfoBar(this, sInfoBar,2000); 改成这样.然后再试试,信息框出来马上点信息框上的关闭按钮.最多二三次就会出现了.

**Comment by mowangshuying** [comment]
嗯

**Comment by mowangshuying** [comment]
要不你提个pr

**Comment by 860000023** [comment]
你直接改吧,我是新手.

**Comment by mowangshuying** [comment]
已修改，谢谢.

**Comment by 860000023** [comment]
大佬客气了,感谢你的开源,可以让我们这些菜鸟学习.^_^

**Comment by mowangshuying** [comment]
重新拉下代码试下，我这边没啥问题了.
