### ISSUE TITLE
请教一下,为何我的FluShortInfoBar 显示的总是不对.

### ISSUE THREAD

**Issue by 860000023** [mowangshuying/CppQtFluentUi888#11]
![info](https://github.com/mowangshuying/CppQtFluentUi888/assets/19246735/f154843f-c130-4e27-8018-5fe0927abed3)
如图.一个是测试工程的.一个是我新建的工程.我把代码拷过去了.同样的方式运行.m_iconLabel的图片像没有显示出来.也没有背景色.不知道为啥 .资源TTF我也单独 测试过.是可以显示图片的,查了好几小时,就是没法像测试工程一样变色,不知道原因在哪里,希望指点一下.

**Comment by mowangshuying** [comment]
没有加载到样式表

**Comment by 860000023** [comment]
还真的是....我再去看看.谢谢.

**Comment by mowangshuying** [comment]
样式表的加载是通过相对路径加载的，工程目录结构截图看下。

**Comment by 860000023** [comment]
好了.唉,查了整整三个小时....哈哈.太菜了.

**Comment by 860000023** [comment]
大佬,我看你在三小时前修复了dark模式下的shotinfobar显示 .但是好像还是存在问题.那个closebtn不会显示. 在light下是正常的.我拿你的测试工程测试过了.也是同样的问题.我想试着自己找出问题,

**Comment by mowangshuying** [comment]
不会吧.

**Comment by mowangshuying** [comment]
截个图看看哪里有问题。

**Comment by mowangshuying** [comment]
![image](https://github.com/mowangshuying/CppQtFluentUi888/assets/46436509/1b6f6725-4c4a-436c-8e67-e74facd8593a)

**Comment by 860000023** [comment]
![111](https://github.com/mowangshuying/CppQtFluentUi888/assets/19246735/81bfc74c-3ec6-4b91-8784-c90ceee836ae)
我再重新拉取一下试试.

**Comment by mowangshuying** [comment]
我修复的是图标显示问题，不是closeBtn的按钮.

**Comment by 860000023** [comment]
FluThemeUtils::getUtils()->setTheme(FluTheme::Dark);
 FluInfoBarDemo demo;
  demo.show();     黑夜模式这样设置是对的吗?我只加上了这一句.就会出现closebtn不显示的问题.

**Comment by mowangshuying** [comment]
调用下FluShortInfoBar的onThemeChanged()函数，在show之前.

**Comment by mowangshuying** [comment]
```cpp
FluInfoBarDemo demo;
demo.show();
// 等控件都准备好后再切换主题色.
FluThemeUtils::getUtils()->setTheme(FluTheme::Dark);
```

**Comment by 860000023** [comment]
FluInfoBarDemo demo;
  demo.show();
 FluThemeUtils::getUtils()->setTheme(FluTheme::Dark); 还是没有效果,我先拿light模式学习吧.才学十多天QT,好多问题都不明白,感谢你的回复.

**Comment by 860000023** [comment]
因为感觉比较酷哈哈.我去弄其它的了,有问题我就记录下来.到时候统一和你反馈.

**Comment by mowangshuying** [comment]
> 因为感觉比较酷哈哈.我去弄其它的了,有问题我就记录下来.到时候统一和你反馈.

你太优秀了，才学十几天就这么厉害了。

**Comment by 860000023** [comment]
大佬你这是调侃我呢.赶紧CLOSE.^_^
