### ISSUE TITLE
Areo窗口失焦前后阴影不一致效果

### ISSUE THREAD

**Issue by CodingDogzxg** [mowangshuying/CppQtFluentUi888#17]
我看到了Gallery窗口失焦前后的窗口阴影都是一致的 这个是由那部分代码控制的 如果我想让窗口恢复Areo失焦后阴影变化效果 是不是将某一部分代码删除掉就可以

**Comment by mowangshuying** [comment]
没有处理Gallery这种失去焦点的情况，Gallery的样式表中也没针对处理的。

**Comment by CodingDogzxg** [comment]
那有可能是FramelessWindow里面的默认处理 我再看下代码吧
