### ISSUE TITLE
项目支持linux系统么

### ISSUE THREAD

**Issue by sudoKs** [mowangshuying/CppQtFluentUi888#20]
如题

**Comment by CodingDogzxg** [comment]
支持的 可以使用cmake qmake构建

**Comment by sudoKs** [comment]
大神,目前有项目微信或者Q群么.
&nbsp;


sudoks
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Richard ***@***.***&gt;; 
发送时间: 2024年7月16日(星期二) 下午3:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mowangshuying/CppQtFluentUi888] 项目支持linux系统么 (Issue #20)














 
支持的 可以使用cmake qmake构建

**Comment by CodingDogzxg** [comment]
不知道 你问下作者吧

**Comment by sudoKs** [comment]
好的,谢谢
&nbsp;


sudoks
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Richard ***@***.***&gt;; 
发送时间: 2024年7月16日(星期二) 下午4:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mowangshuying/CppQtFluentUi888] 项目支持linux系统么 (Issue #20)














 
不知道 你问下作者吧

**Comment by mowangshuying** [comment]
木有.

**Comment by mowangshuying** [comment]
support!
