### ISSUE TITLE
FluFrameLessWidget标题栏出现一条横线

### ISSUE THREAD

**Issue by MyHubTo** [mowangshuying/CppQtFluentUi888#23]
**Describe the bug(描述Bug)**
FluFrameLessWidget标题栏出现一条横线，请问这个在哪里删除？

**To Reproduce(展现Bug)**
运行环境：
   Window 11；
Qt 版本：
  Qt_6_6_0_MSVC2019_64bit；

**Expected behavior(期待效果)**
正常显示标题

**Screenshots(截图)**
代码截图：
![image](https://github.com/user-attachments/assets/83a1bf90-568b-485b-84a3-284b7cdb58f8)
标题栏截图：
![image](https://github.com/user-attachments/assets/f5737643-41a4-4ef6-9ad5-e3f49ffc56b1)

**Comment by mowangshuying** [comment]
是的，我也发现了，暂时无处理办法.

**Comment by mowangshuying** [comment]
你这个不太正常了.

**Comment by mowangshuying** [comment]
Demo里边有提供一个FrameLess的例子，FluTemplateDemo.

**Comment by MyHubTo** [comment]
删掉new FluVNavigationView(this) 好了。这个是啥情况？

**Comment by mowangshuying** [comment]
FluNavigationView用法不对.

**Comment by mowangshuying** [comment]
...
