### ISSUE TITLE
报好多错误，什么原因？

### ISSUE THREAD

**Issue by yangZhiFi** [mowangshuying/CppQtFluentUi888#3]
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	MSB4181	“QtRunWork”任务返回了 false，但未记录错误。	FluControls	C:\Users\erxi\AppData\Local\QtMsBuild\qt_globals.targets	272		
错误	LNK1181	无法打开输入文件“FluControls.lib”	FluIconTool	D:\github_Installation_package\CppQtFluentUi888\FluIconTool\LINK	1		
错误	C1083	无法打开包括文件: “FramelessHelper/Widgets/FramelessWidget”: No such file or directory	FluWinGallery	D:\github_Installation_package\CppQtFluentUi888\FluControls\FluFrameLessWidget.h	3		
错误	C1083	无法打开包括文件: “FramelessHelper/Widgets/FramelessWidget”: No such file or directory	FluWinGallery	D:\github_Installation_package\CppQtFluentUi888\FluControls\FluFrameLessWidget.h	3		
错误	LNK1181	无法打开输入文件“FluControls.lib”	FluExamples	D:\github_Installation_package\CppQtFluentUi888\FluExamples\LINK	1

**Comment by mowangshuying** [comment]
路径设置不对

**Comment by mowangshuying** [comment]
看下项目属性，依赖的头文件目录和lib目录修改下

**Comment by yangZhiFi** [comment]
> 看下项目属性，依赖的头文件目录和lib目录修改下

解决了，就是Qebug版本有点卡。

**Comment by mowangshuying** [comment]
是的，Debug比较卡，release就不会了.
