### ISSUE TITLE
FluDropDownButton类的addIconTextItem方法无法将类型 QIcon 的右值转换为形参类型 FluAwesomeType

### ISSUE THREAD

**Issue by Yecgaa1** [mowangshuying/CppQtFluentUi888#31]
![image](https://github.com/user-attachments/assets/146265b0-46a1-45e8-8229-322d79f892af)
这是例程的代码

而上面的setIcon却可以正常运行，究其原因是addIconTextItem接受的类型是FluAwesomeType而不是QIcon
```c++
button->setIcon(QIcon(FluIconUtils::getFluentIcon(FluAwesomeType::Mail)));
```
感觉像是重构代码留下来的未更改方法

**Comment by mowangshuying** [comment]
嗯

**Comment by mowangshuying** [comment]
这是哪个文件？

**Comment by Yecgaa1** [comment]
#32 这个

**Comment by Yecgaa1** [comment]
#33

**Comment by Yecgaa1** [comment]
这个文件，刚刚提完request后发现好像忽略了你原来setIcon的写法。
方法上setIcon可以同时接受FluAwesomeType和QIcon并且会针对性的做出处理，我模仿这个方法对addIconTextItem进行了补充重构，而原来addIconTextItem接受FluAwesomeType的方法实现似乎和setIcon方法也不一致，我也将其一致化了。

> #33

**Comment by mowangshuying** [comment]
嗯
