### ISSUE TITLE
2024-09-16 16:34:41 [fatal][unknown--423]:ASSERT failure in QList::at: "index out of range", file C:\Qt\6.5.3\msvc2019_64\include\QtCore/qlist.h, line 423 

### ISSUE THREAD

**Issue by Yecgaa1** [mowangshuying/CppQtFluentUi888#34]
![image](https://github.com/user-attachments/assets/57038644-20d3-4142-9814-873b8b2d3382)
这个问题比较奇怪，不能很稳定的复现，有时候重新编译就没事了
但是在不同电脑但相同的编译链环境下都出现了
让我有点不太理解
爆栈的原因是fontFamilies事实上是空的，老实说这很奇怪
![image](https://github.com/user-attachments/assets/11aaa0bf-0748-40b2-ae5b-c7b5876f1fbc)

**Comment by Yecgaa1** [comment]
哦，我知道为什么了，因为部分qss文件无法加载导致的
因为我的调试目录中，res和可执行文件是同层的，而控件默认会去上一层寻找res文件夹
我有两个可供参考的建议：

1. 是否应该检测一下res文件具体在这一层还是上一层目录中呢？
2. 是否应该考虑更优雅的抛出错误而不是直接让qlist抛出index out of range这种不太好检查的错误呢？

仅供参考，顺祝中秋快乐

**Comment by mowangshuying** [comment]
晚上联系下我看看哈.

**Comment by mowangshuying** [comment]
你用的是clion吧，有些时候clion的一些CMake配置会不对。Qt Creator应该是没有这个情况的.

**Comment by Yecgaa1** [comment]
> 你用的是clion吧，有些时候clion的一些CMake配置会不对。Qt Creator应该是没有这个情况的.

那确实是CLion。但是我觉得在完成程序构建打包后，res文件夹的位置应该由用户决定，而不是直接写死在这个路径上，具体可以用条件编译确定，即如果用户没有define路径，则自动define到../res目录中。
如果可以，我可以贡献这个代码

**Comment by mowangshuying** [comment]
master分支采用是资源文件夹的形式，res采用qrc模式，资源被直接编译到代码中.
不知道你有没有发现有一个build&pack.bat，点击它自动就给你打包了。不过可能需要修改下里边的Qt安装目录.
> 是否应该检测一下res文件具体在这一层还是上一层目录中呢？
> 这个可以加下，判断有没有res文件夹没有直接报错.

**Comment by mowangshuying** [comment]
> > 你用的是clion吧，有些时候clion的一些CMake配置会不对。Qt Creator应该是没有这个情况的.
> 
> 那确实是CLion。但是我觉得在完成程序构建打包后，res文件夹的位置应该由用户决定，而不是直接写死在这个路径上，具体可以用条件编译确定，即如果用户没有define路径，则自动define到../res目录中。 如果可以，我可以贡献这个代码

这个修改起来比较费工夫，主要是要替换代码里边的全部资源路径，如果有一个便捷又快的方法这个也可以改.

**Comment by Yecgaa1** [comment]
> master分支采用是资源文件夹的形式，res采用qrc模式，资源被直接编译到代码中. 不知道你有没有发现有一个build&pack.bat，点击它自动就给你打包了。不过可能需要修改下里边的Qt安装目录.
> 
> > 是否应该检测一下res文件具体在这一层还是上一层目录中呢？
> > 这个可以加下，判断有没有res文件夹没有直接报错.

你说的是qrc分支会把资源打包进去程序里面吧？还是说我理解不到位
我看到build&pack.bat，因为我的仓库现在也在用你的action文件，研究的时候看到了，但是这个bat也只是把文件复制到程序上一级的目录吧

**Comment by Yecgaa1** [comment]
> > > 你用的是clion吧，有些时候clion的一些CMake配置会不对。Qt Creator应该是没有这个情况的.
> > 
> > 
> > 那确实是CLion。但是我觉得在完成程序构建打包后，res文件夹的位置应该由用户决定，而不是直接写死在这个路径上，具体可以用条件编译确定，即如果用户没有define路径，则自动define到../res目录中。 如果可以，我可以贡献这个代码
> 
> 这个修改起来比较费工夫，主要是要替换代码里边的全部资源路径，如果有一个便捷又快的方法这个也可以改.

感觉想要写的话替换一下现在的目录路径为宏定义就行，可以我来处理

**Comment by Yecgaa1** [comment]
也行吧，那就先这么用着吧
也就我多处理一行的事情

**Comment by Yecgaa1** [comment]
虽然但是，我觉得给用户个选择权也算可以提升一下健全性？比如用户想放专门的res文件夹呢）
