### ISSUE TITLE
mingw支持

### ISSUE THREAD

**Issue by kaminged** [mowangshuying/CppQtFluentUi888#9]
framelesshelper这个依赖是必要的吗，framelesshelper不支持mingw编译，需要llvm-mingw

**Comment by mowangshuying** [comment]
支持吧，用Qt Creator打开CMakeLists.txt.

**Comment by mowangshuying** [comment]
已经源码引入了frameless-2.5.0

**Comment by kaminged** [comment]
我再Windows上使用的QT 6.6.3 mingw + CMake方式命令行编译，看到framelesshelper依赖中utils.cmake中有检测不支持mingw编译, 需要安装llvm-mingw

**Comment by mowangshuying** [comment]
![image](https://github.com/mowangshuying/CppQtFluentUi888/assets/46436509/d3e1d494-0db7-464e-af21-cdcd7ae997af)

**Comment by mowangshuying** [comment]
这个或许有点帮助.
